### ISSUE TITLE
comment

### ISSUE THREAD

**Issue by marwa7med** [facg3/msn-currencies-changes#18]
i notice that you have many line of unusefull comment you should deleat it 
![image](https://user-images.githubusercontent.com/30667339/33702727-99d5b480-db2d-11e7-99c9-20a2b6687acc.png)
![image](https://user-images.githubusercontent.com/30667339/33702755-b902819e-db2d-11e7-9cf4-1a69e630f117.png)

**Comment by NadiaKhatib** [comment]
Done :+1:
