### ISSUE TITLE
unused files.

### ISSUE THREAD

**Issue by sultanassi95** [facg3/msn-currencies-changes#8]
this is linked to this issue (https://github.com/facg3/JokeGenerator/issues/21)
un used file:
msn-currencies-changes/src/tests/logic.test.js
msn-currencies-changes/src/logic.js

**Comment by NadiaKhatib** [comment]
Done :+1:

**Comment by sultanassi95** [comment]
I have checked out your master branch, but nothing has changed. are you sure it's done?
